### ISSUE TITLE
In the drawings some measures are missing a decimal separator 

### ISSUE THREAD

**Issue by The-Force** [function3d/petalot#1]
Not a big deal but In the drawings some measures are missing a decimal separator:
![image](https://user-images.githubusercontent.com/1139548/195846208-b26fe272-d086-4bee-b56b-919fa8f4a801.png)
![image](https://user-images.githubusercontent.com/1139548/195846343-4cf96178-ce81-4f03-9023-ba162e83f078.png)

**Comment by function3d** [comment]
Thanks for the warning, I will correct it soon

**Comment by function3d** [comment]
drawing fixed
