### ISSUE TITLE
BOM File is deleted from google sheets

### ISSUE THREAD

**Issue by canberkkurtulmus** [function3d/petalot#11]
Hi,

I couldn't get the BOM sheet because it says that it is deleted. Can you provide it please?

Thanks

**Comment by function3d** [comment]
From the readme.md file (English version) https://docs.google.com/spreadsheets/d/1QrsbV1TAUxwC-E0CKtm_DCh9_VTj5VazpKik1_OQ4T8/edit?usp=sharing

Sorry, the BOM link from LEEME.md (Spanish version) is broken
