### ISSUE TITLE
electronics

### ISSUE THREAD

**Issue by sirrober126** [function3d/petalot#13]
I was looking for the electronics part. yet the BOM has been deleted. is there an updated version?

**Comment by function3d** [comment]
The link works for me, I don't understand it 

https://docs.google.com/spreadsheets/d/1QrsbV1TAUxwC-E0CKtm_DCh9_VTj5VazpKik1_OQ4T8

**Comment by sirrober126** [comment]
> 

thanks. i got it. I also figured out the why. I was on a computer that had that type command blocked
