### ISSUE TITLE
I would get the linked psu into the electronics box

### ISSUE THREAD

**Issue by hibobly** [function3d/petalot#17]

**Comment by function3d** [comment]
Can you explain better?

**Comment by hibobly** [comment]
sorry for the spelling mistakes but the electronics is 7 cm wide and the linked psu is 7.8 cm wide

**Comment by function3d** [comment]
12V 5A power supply is 58mm 
![IMG20230201091937](https://user-images.githubusercontent.com/109918879/215988681-0c71128e-0673-4c91-aeea-b6a2986deb62.jpg)

**Comment by hibobly** [comment]
thanks
