### ISSUE TITLE
Always false condition in hotend.hpp

### ISSUE THREAD

**Issue by javiersanzsanchez** [function3d/petalot#2]
On strat method the condition "if (tempLastStart == 0)" will never be true do to "tempLastStart = millis();" on previous line.

![Captura de pantalla 2022-10-27 a las 10 49 34](https://user-images.githubusercontent.com/16131716/198238390-f031df91-ad6d-4dec-ac9e-ec5610d1ca3a.png)

**Comment by function3d** [comment]
In the "stop" method there is a "tempLastStart=0" so after a manual or end filament "Stop" event, "if (tempLastStart == 0)" will be true

**Comment by javiersanzsanchez** [comment]
I think no... you set "tempLastStart = millis();" so it will never be zero after that, I mean the second if.

**Comment by function3d** [comment]
the code of the start method is only executed the first time it is called after a stop, the following times it is called it is not executed because of that condition

**Comment by function3d** [comment]
the code of the start method only needs to be executed once after a stop, the following times are redundant and have no effect

**Comment by function3d** [comment]
anyway, what issue is this condition causing you?

**Comment by javiersanzsanchez** [comment]
No, is not completed. This amateur programming practice is still present.

**Comment by function3d** [comment]
I'm not going to recode something that works no matter how amateurish you think it is
