### ISSUE TITLE
stepper motor driver does not show any reading when you turn the potentiometer

### ISSUE THREAD

**Issue by hibobly** [function3d/petalot#20]
when every thing is attached the stepper motor does not move and stepper motor driver does not show a reading on the pot.
and help would be appreciated.

**Comment by function3d** [comment]
Check that it is connected in the correct position and try another one

**Comment by function3d** [comment]
Check your welds, make sure you do not have two adjacent welds joined together.

**Comment by function3d** [comment]
Check your welds, make sure you do not have two adjacent welds joined together.
