### ISSUE TITLE
Stepper motor doesnt work

### ISSUE THREAD

**Issue by MarmotLand** [function3d/petalot#21]
A recently set up everything and it works but accept for stepper motor I set up the the voltage 0.4 V the stepper motor doesnt do anything any noise any spin nothing THANKS for help

**Comment by bujary** [comment]
Did you buy the stepper motor indicated in the video and another? if it is another one, make sure its vref and readjust the driver voltage

**Comment by MarmotLand** [comment]
> Did you buy the stepper motor indicated in the video and another? if it is another one, make sure its vref and readjust the driver voltage

Im using NEMA 17 17HS3401 and it wokrs perfectly with my 3D printer , I was also using it for another PET filament machine and it was working with no issues . I reacently came up to a conclusion that the stepper motor driver might be burnt , because I accidently disconnected the steper motor while i was testing it. Thanks for replying

**Comment by bujary** [comment]
You're welcome

**Comment by function3d** [comment]
Check your welds, make sure you do not have two adjacent welds joined together
