### ISSUE TITLE
Wemos D1 Mini (4mb) fried

### ISSUE THREAD

**Issue by Biospargel** [function3d/petalot#22]
Hi,I'm a big fan from Germany, we recently build your machine with the pcb (manufactured at JLCPCB) and all components for a school project. I set everything up and turned the potentiometers correctly, but as I turned on the whole system the wemos rustle and the led didn't get that bright anymore. I can't flash it right now because it gets very hot while writing.

I don't know if it's my fault, but I rule out a short circuit.

can I repair the wemos?

Thanks for that cool project!!!

**Comment by function3d** [comment]
Hi Till,

I don't think it can be repaired, you should try another one and make sure
you plug it in the correct position and power it with 5 volts.

Good luck,

Raúl, Function.3D
