### ISSUE TITLE
Just a little doubt

### ISSUE THREAD

**Issue by RuhtraXD** [function3d/petalot#23]
For power do you use 2 positive and negative 12V wires connected to the board? Is there no risk of closing the circuit?

**Comment by function3d** [comment]
I don't understand your question, every electrical circuit needs two wires
(positive and negative) to be powered.

**Comment by RuhtraXD** [comment]
I mean, should I use 12V positive and 12V negative or should I use 12V positive and negative?

**Comment by function3d** [comment]
Of course, you must use 12V and ground

**Comment by RuhtraXD** [comment]
Understood, thanks for the assistance, you're doing a great job with this project.

**Comment by bujary** [comment]
ruhtra meu novo dc sparkinho_ pede amizade
