### ISSUE TITLE
Heatblock not heating

### ISSUE THREAD

**Issue by Biancod** [function3d/petalot#24]
Hi, my heatblock it’s not heating, i’m not getting current on heaters pin, what should i check?

**Comment by function3d** [comment]
Check the MOSFET

**Comment by function3d** [comment]
Check your welds, make sure you do not have two adjacent welds joined together.

**Comment by function3d** [comment]
Check your welds, make sure you do not have two welds next to each other

**Comment by function3d** [comment]
make sure there is no weld making bad contact
