### ISSUE TITLE
Stepper motor doesnt spin

### ISSUE THREAD

**Issue by Adam3359** [function3d/petalot#25]
Hi, Function3d i have issue with my stepper motor it doesnt want to spin, I tried everything and still it doesnt want to work. What i should check ?. Thanks for respond

**Comment by function3d** [comment]
1.
https://github.com/function3d/petalot/blob/5b1d409dda7f66e7040381943212c45b0bf8b62b/before%20you%20switching%20on%20the%20electronics.md

2. Check the connectors.

3. Test the motor in your 3D printer.

4. Try another stepper driver.

**Comment by Adam3359** [comment]
I tried everything, but still it doesnt want to spin

**Comment by function3d** [comment]
Check your welds, make sure you do not have two adjacent welds joined together.
