### ISSUE TITLE
d1 mini does not create wifi network

### ISSUE THREAD

**Issue by RuhtraXD** [function3d/petalot#26]
I followed every step by step but the arduino does not create the wifi network called petalot.

**Comment by gulsinho06** [comment]
Instale o driver do esp8266 para o chip CH340G e compile novamente

**Comment by bujary** [comment]
Install esp8266 driver for CH340G chip and compile again

**Comment by RuhtraXD** [comment]
Where can i get this esp8266?

**Comment by RuhtraXD** [comment]
Plis can you make a more detailed step by step, im thinking im doing something wrong.

**Comment by bujary** [comment]
Okay, the tutorial is in portuguese but you can translate https://www.robocore.net/tutoriais/instalando-driver-do-nodemcu
you must install CH340g driver
OR
https://www.youtube.com/watch?v=WnRk8w7SyTo&ab_channel=SimpleElectronics

**Comment by RuhtraXD** [comment]
Alright, the first tutorial i already done yesterday and it doens't work (portuguese is not a problem, im brazilian) and now i've this second tutorial, now i can flash the program on the arduino normally?

**Comment by bujary** [comment]
Sou br tbm posso tentalo ajudalo meu dc para contato: SPARKINHO#9289 

E sim dps do driver so fazer o flash no programa que ele indicou que dah certo.

**Comment by RuhtraXD** [comment]
Seu perfil não aceita pedido, Ruhtra#6973 tenta o meu.
