### ISSUE TITLE
Which board to use in Arduino IDE?

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#28]
Inside the Arduino IDE there are these boards

LOLIN(WEMOS) D1 ESP-WROOM-02
LOLIN(WEMOS) D1 R2 & mini
LOLIN(WEMOS) D1 mini (clone)
LOLIN(WEMOS) D1 mini Lite
LOLIN(WEMOS) D1 mini Pro
LOLIN(WeMos) D1 R1

Which one to use with D1 mini v3?

**Comment by function3d** [comment]
LOLIN(WEMOS) D1 R2 & mini
