### ISSUE TITLE
machine the hotend

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#29]
What drills do you use to machine the hotend?

And is there any more didactic tutorial for me to follow?

**Comment by function3d** [comment]
I use one like [this](https://media.adeo.com/marketplace/MKP/84433455/0231d78c41351987282fa4866cc16b91.jpeg?width=650&height=650&format=jpg&quality=80&fit=bounds) (8mm glass drill bit) for the block and nozzle plus 1.7mm drill bit for the nozzle hole. [This](https://youtu.be/dQRuUmIxJyA) is an old video, I am planning a new video with the new drill bit
