### ISSUE TITLE
What filament did you use to print the parts?

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#30]
What filament did you use to print the parts?

**Comment by function3d** [comment]
To date I have manufactured 8 machines, all of them with PET filament from
recycled bottles except the first one which was partially printed with PET
filament from bottles

**Comment by bujary** [comment]
how is my first machine going, would petg be the most recommended? or abs?

**Comment by function3d** [comment]
Yes PETG better than PLA, but PLA should also work

**Comment by Deses** [comment]
> To date I have manufactured 8 machines

Do you sell complete kits, by any chance?

**Comment by function3d** [comment]
I am currently manufacturing on demand. Send me a email to
***@***.*** and I will send you a quote
