### ISSUE TITLE
end of course question!

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#33]
Can I use this one?

https://pt.aliexpress.com/item/1005005327520357.html?spm=a2g0o.cart.0.0.28a27f06D8TvWH&mp=1&gatewayAdapt=glo2bra

**Comment by function3d** [comment]
I don't know the dimensions of that one but if it's not the same it won't
fit.

**Comment by bujary** [comment]
Where can I find the IRLZ44N the link you provided is no longer available

**Comment by function3d** [comment]
https://a.aliexpress.com/_EQTfu8r

https://a.aliexpress.com/_EuAvhxp

**Comment by HumbleDeer** [comment]
> Where can I find the IRLZ44N the link you provided is no longer available

You can use another suitable N-channel MOSFET if you do not have this specific one on hand, as long as the pinout matches and the specifications are roughly enough for the project (eg voltage across it, and the current drawn by the heater)
