### ISSUE TITLE
Dead links to AliExpress

### ISSUE THREAD

**Issue by Deses** [function3d/petalot#35]
I've found some dead links in the BOM, and found some possibly suitable replacements. Please verify if they are the proper ones.

`Mini Micro Limit Switch Roller Lever Arm` --> https://es.aliexpress.com/item/1926553469.html
`IRLZ44N MOSFET` --> https://es.aliexpress.com/item/1005002474344551.html
`capacitor 100uf 16V` --> https://es.aliexpress.com/item/1005002842732971.html
`pin header` --> https://es.aliexpress.com/item/32735482077.html

Also, you should maybe consider migrating the BOM to a Github Wiki page to keep everything in one single resource.

Gracias!

**Comment by Deses** [comment]
Here's the current table (with dead links) in markdown format in case you want to do the switch, saving you some work. :)

### Code:
```
\* These parts are not tested by me because I did not buy them. I replaced them with things I already had.
| Qty    | Name                                                                                          | Aliexpress (for reference)                 |
| ------ | --------------------------------------------------------------------------------------------- | ------------------------------------------ |
| ------ | ----------- **Bottle cutter** ------------------------------------------------- | ------------------------------------------ |
| 2      | bearing 6200 ZZ high speed 10x30x9                                                            | https://s.click.aliexpress.com/e/_DBCB7qJ  |
| \*2    | M8 Hex Bolt 60mm Full Thread                                                                  | https://s.click.aliexpress.com/e/_DF8rC8x  |
| \*3    | Hex Nut M8                                                                                    | https://s.click.aliexpress.com/e/_DdAzvUJ  |
| \*1    | Hexagonal Bolt Partial Thread M8 40mm DIN931                                                  | https://s.click.aliexpress.com/e/_DCCHxur  |
| \*2+   | Flat Washer M8 16x1                                                                           | https://s.click.aliexpress.com/e/_DdBx3SF  |
| \*2    | M8 Hex Nylon Insert Lock Nut Self-locking Locknut                                             | https://s.click.aliexpress.com/e/_At5Tpj   |
| \*1    | Threaded Rod 6mm (any 6mm rod will work, I used a carbon fiber rod from a kite)               | https://s.click.aliexpress.com/e/_DEQQjrz  |
| ------ | ----------- **Electronics** --------------------------------------------------- | ------------------------------------------ |
| 1      | Power Supply 12v 5A                                                                           | https://s.click.aliexpress.com/e/_DEF56Ef  |
| 1      | Wemos D1 MINI V3.0.0                                                                          | https://s.click.aliexpress.com/e/_9GGvad   |
| 1      | Mini DC-DC 12-24V To 5V 3A Step Down                                                          | https://s.click.aliexpress.com/e/_A8abPX   |
| 1      | Mini Micro Limit Switch Roller Lever Arm                                                      | https://s.click.aliexpress.com/e/_AqJnzx   |
| 1      | A4988 DRV8825 Stepper Motor Driver With Heat sink                                             | https://s.click.aliexpress.com/e/_AMKH4t   |
| 1      | Nema 17 stepper motor 42 motor height 38mm 1.2A D shaped shaft                                | https://s.click.aliexpress.com/e/_AfngLT   |
| 1      | IRLZ44N MOSFET                                                                                | https://s.click.aliexpress.com/e/_DkRy2Mx  |
| 1      | Hotend MK8 Extrusion Aluminum Block 20x20x10mm with Thermistor Ceramic and Heater 12V 40W     | https://s.click.aliexpress.com/e/_9QSRwl   |
| \*1    | capacitor 100uf 16V                                                                           | https://s.click.aliexpress.com/e/_DkEQAV5  |
| \*x    | pin header                                                                                    | https://s.click.aliexpress.com/e/_Ddiwa2P  |
| 3      | terminal blocks 2P                                                                            | https://s.click.aliexpress.com/e/_DdfJlAb  |
| \*2    | 10K ohms resistors                                                                            | https://s.click.aliexpress.com/e/_DkDLncf  |
| \*50cm | 2 wire cable for limit switch, digital signal                                                 | https://s.click.aliexpress.com/e/_Dlnn1bd  |
| \*50cm | 2 wire cable for 5A+                                                                          | https://s.click.aliexpress.com/e/_Dlnn1bdd |
| \*1    | 10A 250V Inlet Module Plug Rocker Switch Male Power Socket 3 Pin IEC320 C14 switch + Fuse New | https://s.click.aliexpress.com/e/_DmXiViX  |
| ------ | ----------- **Hardware** ---------------------------------------------------- | ------------------------------------------ |
| 1      | MK8 Brass Nozzle 0.4MM                                                                        | https://s.click.aliexpress.com/e/_ANswWD   |
| 4      | Bearing 8x22x7 mm 608ZZ                                                                       | https://s.click.aliexpress.com/e/_DDu60K3  |
| 1      | Stainless Steel 90 Degree Angle Bracket Corner 20x20mm                                        | https://s.click.aliexpress.com/e/_ACOtVF   |
| \*2    | M8 x 100mm A2 Hex Head Screw Bolt                                                             | https://s.click.aliexpress.com/e/_AY2LNb   |
| \*2    | M8 Hex Nylon Insert Lock Nut Self-locking Locknut                                             | https://s.click.aliexpress.com/e/_At5Tpj   |
| \*1    | M3 8mm Bolt for the motor gear                                                                | https://s.click.aliexpress.com/e/_DelUMSF  |
| \*3    | M3 14mm Bolt for motor mount                                                                  | https://s.click.aliexpress.com/e/_DelUMSF  |
| \*50cm | Paracord 2mm(nylon string) (I used polyester thread for kite handles)                         | https://s.click.aliexpress.com/e/_99oV2Hv  |
| \*1    | 1.7mm drill bit                                                                               | https://s.click.aliexpress.com/e/_DD1SYVV  |
```
### And how it looks:
\* These parts are not tested by me because I did not buy them. I replaced them with things I already had.
| Qty    | Name                                                                                          | Aliexpress (for reference)                 |
| ------ | --------------------------------------------------------------------------------------------- | ------------------------------------------ |
| ------ | ----------- **Bottle cutter** ------------------------------------------------- | ------------------------------------------ |
| 2      | bearing 6200 ZZ high speed 10x30x9                                                            | https://s.click.aliexpress.com/e/_DBCB7qJ  |
| \*2    | M8 Hex Bolt 60mm Full Thread                                                                  | https://s.click.aliexpress.com/e/_DF8rC8x  |
| \*3    | Hex Nut M8                                                                                    | https://s.click.aliexpress.com/e/_DdAzvUJ  |
| \*1    | Hexagonal Bolt Partial Thread M8 40mm DIN931                                                  | https://s.click.aliexpress.com/e/_DCCHxur  |
| \*2+   | Flat Washer M8 16x1                                                                           | https://s.click.aliexpress.com/e/_DdBx3SF  |
| \*2    | M8 Hex Nylon Insert Lock Nut Self-locking Locknut                                             | https://s.click.aliexpress.com/e/_At5Tpj   |
| \*1    | Threaded Rod 6mm (any 6mm rod will work, I used a carbon fiber rod from a kite)               | https://s.click.aliexpress.com/e/_DEQQjrz  |
| ------ | ----------- **Electronics** --------------------------------------------------- | ------------------------------------------ |
| 1      | Power Supply 12v 5A                                                                           | https://s.click.aliexpress.com/e/_DEF56Ef  |
| 1      | Wemos D1 MINI V3.0.0                                                                          | https://s.click.aliexpress.com/e/_9GGvad   |
| 1      | Mini DC-DC 12-24V To 5V 3A Step Down                                                          | https://s.click.aliexpress.com/e/_A8abPX   |
| 1      | Mini Micro Limit Switch Roller Lever Arm                                                      | https://s.click.aliexpress.com/e/_AqJnzx   |
| 1      | A4988 DRV8825 Stepper Motor Driver With Heat sink                                             | https://s.click.aliexpress.com/e/_AMKH4t   |
| 1      | Nema 17 stepper motor 42 motor height 38mm 1.2A D shaped shaft                                | https://s.click.aliexpress.com/e/_AfngLT   |
| 1      | IRLZ44N MOSFET                                                                                | https://s.click.aliexpress.com/e/_DkRy2Mx  |
| 1      | Hotend MK8 Extrusion Aluminum Block 20x20x10mm with Thermistor Ceramic and Heater 12V 40W     | https://s.click.aliexpress.com/e/_9QSRwl   |
| \*1    | capacitor 100uf 16V                                                                           | https://s.click.aliexpress.com/e/_DkEQAV5  |
| \*x    | pin header                                                                                    | https://s.click.aliexpress.com/e/_Ddiwa2P  |
| 3      | terminal blocks 2P                                                                            | https://s.click.aliexpress.com/e/_DdfJlAb  |
| \*2    | 10K ohms resistors                                                                            | https://s.click.aliexpress.com/e/_DkDLncf  |
| \*50cm | 2 wire cable for limit switch, digital signal                                                 | https://s.click.aliexpress.com/e/_Dlnn1bd  |
| \*50cm | 2 wire cable for 5A+                                                                          | https://s.click.aliexpress.com/e/_Dlnn1bdd |
| \*1    | 10A 250V Inlet Module Plug Rocker Switch Male Power Socket 3 Pin IEC320 C14 switch + Fuse New | https://s.click.aliexpress.com/e/_DmXiViX  |
| ------ | ----------- **Hardware** ---------------------------------------------------- | ------------------------------------------ |
| 1      | MK8 Brass Nozzle 0.4MM                                                                        | https://s.click.aliexpress.com/e/_ANswWD   |
| 4      | Bearing 8x22x7 mm 608ZZ                                                                       | https://s.click.aliexpress.com/e/_DDu60K3  |
| 1      | Stainless Steel 90 Degree Angle Bracket Corner 20x20mm                                        | https://s.click.aliexpress.com/e/_ACOtVF   |
| \*2    | M8 x 100mm A2 Hex Head Screw Bolt                                                             | https://s.click.aliexpress.com/e/_AY2LNb   |
| \*2    | M8 Hex Nylon Insert Lock Nut Self-locking Locknut                                             | https://s.click.aliexpress.com/e/_At5Tpj   |
| \*1    | M3 8mm Bolt for the motor gear                                                                | https://s.click.aliexpress.com/e/_DelUMSF  |
| \*3    | M3 14mm Bolt for motor mount                                                                  | https://s.click.aliexpress.com/e/_DelUMSF  |
| \*50cm | Paracord 2mm(nylon string) (I used polyester thread for kite handles)                         | https://s.click.aliexpress.com/e/_99oV2Hv  |
| \*1    | 1.7mm drill bit                                                                               | https://s.click.aliexpress.com/e/_DD1SYVV  |

**Comment by function3d** [comment]
done, thanks for the suggestion and help
