### ISSUE TITLE
Configs!

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#36]
What do the abbreviations of the configuration that you have on the site mean

    To
    Vo 
    Tm 
    Kp 
    Ki
    Kd 
    Max 
    R1 
    ifttt_event_name
    ifttt_api_key

**Comment by function3d** [comment]
Kp, Ki, and Kd are parameters commonly used in the PID (Proportional,
Integral, Derivative) controller. Kp is the proportional constant, Ki is
the integral constant, and Kd is the derivative constant.

R1 is the actual value of the PCB resistor R1, it is not important to be
precise with this
