### ISSUE TITLE
Nema 17

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#38]
Is it okay if I use a nema 17 4.2 kgf? Same dimensions as the project, it can only hold more kgf

**Comment by function3d** [comment]
Surely you can

**Comment by Thorgal10** [comment]
If I connect the 12Volt then the components start to smoke

**Comment by function3d** [comment]
You did something wrong before https://vm.tiktok.com/ZGJuB6V5r/

**Comment by Thorgal10** [comment]
my connection of my capacitor begins to sizzle
![IMG_20230501_145103 (1)](https://user-images.githubusercontent.com/96912169/235454337-77910b29-a1e4-41b5-8a35-39c83ba6a020.jpg)

**Comment by function3d** [comment]
Link to that capacitor?

**Comment by Thorgal10** [comment]
I think I found it, it was the leftover of the solder fluid that was causing a short circuit.

**Comment by Thorgal10** [comment]
sorry,now i cant find the port for the flash
