### ISSUE TITLE
Include ESPHome config file

### ISSUE THREAD

**Issue by HumbleDeer** [function3d/petalot#39]
The ESPHome config file is required to modify the firmware. Included in the repository is only the files that ESPHome generated using the PlatformIO environment, but this is not enough to recreate the ESPHome project if any adjustments to firmware are required.

The original ESPHome config file comes in the form of a .yaml file.

**Comment by function3d** [comment]
There's no ESPHome config, It is a Arduino IDE project

**Comment by HumbleDeer** [comment]
Oh, how come the use of ESPHome as a platform then?

**Comment by function3d** [comment]
I don't know what ESPHome is, I just use the Arduino IDE.

**Comment by HumbleDeer** [comment]
It's mentioned on the readme for the firmware as a requirement. 😅
![Screenshot_20230503-093928](https://user-images.githubusercontent.com/16231288/235857398-cc63e7e1-ee9c-41a7-9c7c-e7403b814fb0.png)
If you use just Arduino, I will look into making some small improvements to the code to make it C++ standard compliant (proper usage of header files etc)

**Comment by function3d** [comment]
Esphome-flasher is a software only for loading firmware compiled by Arduino
IDE

**Comment by HumbleDeer** [comment]
I see.
I'll do some work on the firmware then, and plan on adding some optional
features I'd like to have. I'll do that on my fork. Cheers.
