### ISSUE TITLE
Need of deactivating the 3g/4g connection before trying to conect to the "petalot" ssid

### ISSUE THREAD

**Issue by JesConsuegra** [function3d/petalot#40]
@function3d Please add to the documentation the need of deactivating the 3G/4G connection in the Android phone, if not there is no connection possible. Thanks.

**Comment by function3d** [comment]
The problem you report does not seem to be something absolute, I have tested it from my android phone and I have not needed to disable the 3G/4G connection.

**Comment by function3d** [comment]
I added a comment to the instructions in case the same thing happens to someone else.

**Comment by JesConsuegra** [comment]
> I added a comment to the instructions in case the same thing happens to someone else.

Thanks a lot!
