### ISSUE TITLE
Stepper motor problem

### ISSUE THREAD

**Issue by eteache** [function3d/petalot#43]
Hi,

I've assembled everything, but the motor doesn't turn. What checks can I do? 
Is it normal for the motor driver to get so hot even with the heat sink?

**Comment by function3d** [comment]
Hi,  you probably have a short circuit, check the adjoining welds that are
not communicating.

**Comment by scalinux** [comment]
Try testing the motor without drive using this as example. Also check youtube videos explain how to. Good luck!

![image](https://github.com/function3d/petalot/assets/65316160/e330e319-db8f-49e0-ab11-824cbe80ce6c)

**Comment by eteache** [comment]
Motor is fine, tried to connect directly to my 3D printer and works fine. After two boards built, I think I'm welding bad some component...
