### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#44]
For which board should I compile the code? inside the esp8266 library

**Comment by function3d** [comment]
![image](https://github.com/function3d/petalot/assets/109918879/3cc3ae06-480a-4400-8a57-383b2a032dfd)

**Comment by function3d** [comment]
this is my complete list of libraries, it doesn't mean that all of them are necessary to compile the firmware, but they are all the ones that I currently have and the firmware compiles for me:

![image](https://github.com/function3d/petalot/assets/109918879/06e7e007-60a9-4ee8-8c77-55f04fc00f30)
![image](https://github.com/function3d/petalot/assets/109918879/d1828154-be02-43a2-9240-6b1f5d201dff)
![image](https://github.com/function3d/petalot/assets/109918879/0774830c-abcc-4205-bf21-93a020a5269d)
![image](https://github.com/function3d/petalot/assets/109918879/f15850ff-9e56-44dc-98f3-65e869cbc570)
![image](https://github.com/function3d/petalot/assets/109918879/3773e839-9239-45fb-9b5d-28d2f52753e8)
![image](https://github.com/function3d/petalot/assets/109918879/8fcebef6-33e4-4f82-a7fe-da96bb41634d)
