### ISSUE TITLE
Filament clogged

### ISSUE THREAD

**Issue by frosty884** [function3d/petalot#45]
![image](https://github.com/function3d/petalot/assets/15754873/bf978aa3-fe3b-49c3-9b54-3ea94caa4914)

The strip is 0.25mm x 9mm.

The temperature I have changed to various points from 220-250C.  I have also tried to lower the speed.  The hotend is tested with thermometer and reads correct values.  I already have ~10cm of pulled filament, but once the strip gets to its widest point, it refuses to pull, resulting in system failure.  How can I fix this, thank you.

**Comment by function3d** [comment]
Either the strip passes or it does not pass, if it does not pass you have to cut it narrower, if you cannot pull it by hand, the motor cannot either.
