### ISSUE TITLE
Help-me

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#47]
what is the cutting width of the pet bottle? because I did all the tutorial and I can't make the filament go through the hotend

**Comment by function3d** [comment]
https://function3d.xyz/en/?Display_FAQ=267

The plastic strip must be able to be pulled by hand, if you can't pull it
by hand the motor will not be able to pull it either.

**Comment by scalinux** [comment]
You can follow this short, from the official YouTube channel. 
https://youtu.be/0TZXpEN6e_o

![image](https://github.com/function3d/petalot/assets/65316160/0f921ac1-411c-4ebd-82ad-af460df2f8e1)
