### ISSUE TITLE
ABOUT ESP8266MOD Flash

### ISSUE THREAD

**Issue by scalinux** [function3d/petalot#49]
After flash the module it get into a loop reboot. 

Re flash with original dump firmware from manufacture and get back to normal. ESP8266MOD USB-C type. ![image](https://github.com/function3d/petalot/assets/65316160/0382245d-76b1-4b41-803e-563ec7b69e16)

**Comment by function3d** [comment]
This is not the module for which the firmware is compiled

**Comment by scalinux** [comment]
Thanks.
After testing and testing keep trying the .bin file. Manage to make it work without using the flash ESPTool recommended on the firmware article. 

The only change in this module is USB-C. The only way get it to flashes is via web interface ESP Web Tool, using MacBook Pro M2.

First need to flash with official ESP HOME. Second step set WIFI. Then using the https://web.esphome.io click Connect then Install the PETALOT firmware.

Make sure connect 3V on the pins. Then the USB-C to flash.

![image](https://github.com/function3d/petalot/assets/65316160/a289585b-1df8-40fd-b5c5-805252d875ac)

Then flash Official ESPHome.
![image](https://github.com/function3d/petalot/assets/65316160/323cdd7c-a0e8-4614-bf64-5ffb13fc03cf)

Or web Tool.
![image](https://github.com/function3d/petalot/assets/65316160/6c26f9a7-7638-439b-8e24-265392330182)

Then as usual test the local ip web interface. 

![image](https://github.com/function3d/petalot/assets/65316160/8e3d949a-135b-43d7-855c-8076c6f08e68)

Your.bin file loaded in the Mini D1 USB-C 


Thanks for sharing this project.
#scalinux

**Comment by function3d** [comment]
Thank you very much for that exhaustive documentation of the case

**Comment by scalinux** [comment]
Makes sure to add this to the article for GNU/Linux/MAC users.

Thanks..

**Comment by function3d** [comment]
I am a Linux user and the steps I describe work well for me.
