### ISSUE TITLE
Motor does not change speed

### ISSUE THREAD

**Issue by kartonkafoto** [function3d/petalot#51]
Motor does not change speed when i change it in web-interface. The speed remains 20 mm/min always. It would be great to make a slider to change the speed.

**Comment by function3d** [comment]
20cm/minute is the maximum and 10cm/minute the minimum

**Comment by kartonkafoto** [comment]
20cm/minute is so low speed. Can you make max\min values in settings for change it by user?

**Comment by function3d** [comment]
The electronics cannot move the stepper motor faster, 20 is the limit, but
also and much more important the PET cannot be made faster, it needs time
to warm up.

**Comment by kartonkafoto** [comment]
I make petalot on the other size of gears. PetPULL project gears. I need high speed.
