### ISSUE TITLE
screws

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#52]
What screw did you use to screw the pieces to the wood? and what screw did you use to screw the  spool holder to the wood?

**Comment by function3d** [comment]
![IMG20230924184112](https://github.com/function3d/petalot/assets/109918879/b4f3470a-9c6a-4c86-b02c-8e84772cabe8)

**Comment by gulsinho06** [comment]
the screw that locks the motor gear Can I use an m3x8 allen screw?
