### ISSUE TITLE
WIFI SECURITY

### ISSUE THREAD

**Issue by bujary** [function3d/petalot#55]
where do I set the wifi password?

**Comment by function3d** [comment]
There is no password for the PETALOT-XXXXXX wifi, you can connect to your
home wifi as a client from the settings so the PETALOT-XXXXXX wifi will no
longer exist.

**Comment by bujary** [comment]
I wanted to put a password, how do I do it?

**Comment by function3d** [comment]
You will have to program the code and compile new firmware
