### ISSUE TITLE
Dificultad para cortar botellas.

### ISSUE THREAD

**Issue by otenmas** [function3d/petalot#59]
Hola, gracias por el proyecto, los vídeos y por ser de ayuda.
Todavía no he descubierto qué estoy haciendo mal pero no puedo cortar las botellas.
Había invertido los rodamientos, donde el rodamiento más alto estaba en el lado donde descansa la garra. Lo arreglé.
Sin embargo, cuando empiezo a tirar de la tira, la botella "sube" y se sale de la "guía", y la tira se estrecha y se rompe. O la botella sigue moviéndose hacia arriba y hacia abajo por la guía y la tira no tiene un tamaño uniforme.

ola, obrigado pelo projeto, pelos videos e por ser solicito.
eu ainda nao descobri o que eu estou fazendo de errado mas eu nao estou conseguindo cortar as garrafas. 
Eu tinha invertido os rolamentos, onde o rolamento mais alto ficava do lado onde se apoia a garrava. consertei isto.
Porem quando eu começo a puxar a tira, a garrafa "sobe" e sai do "guia", e a tira se estreita e parte. Ou a garrafa fica subindo e descendo do guia e a tira nao fica com tamanho uniforme.
![20240110_204928](https://github.com/function3d/petalot/assets/142825517/ea20c818-32cb-4c29-9772-1f817786c0ae)
![20240110_204934](https://github.com/function3d/petalot/assets/142825517/aac81461-ac01-427e-9031-e0c8a7a2293f)
![20240110_205105](https://github.com/function3d/petalot/assets/142825517/d412aa25-292a-4b8b-9151-2fd69e877eb2)
![20240110_205113](https://github.com/function3d/petalot/assets/142825517/652fd831-8bd1-4c0c-b361-fd66f9454cdf)
![20240110_205348](https://github.com/function3d/petalot/assets/142825517/ff6a414c-b20f-4c36-86a5-9ac7786881fe)
![20240110_205759](https://github.com/function3d/petalot/assets/142825517/433d1e4e-5bd4-445a-8779-2602fd107c00)

**Comment by JesConsuegra** [comment]
Hola Samuel. Yo he montado varios (gracias @function3d  por el diseño) y por lo que veo en tus fotos el corte no es limpio, el afilado de los bordes del rodamiento no debe estar en condiciones. Cuando corta bien va muy suave y queda un corte muy limpio, sin rebabas y suave al tacto. Por otra parte hace falta algún peso para mantener la garrafa en contacto con la base, yo uso una bobina vacía de las de PLA puesta encima del cuello de la garrafa, y con eso va bien. Depende del peso de la bobina puede que haya que poner dos en vez de una. Prueba de "afilar" el rodamiento pasándolo por encima de una hoja de papel de lija sobre una madera plana (con plancha de melamina encima, por ejemplo).

**Comment by otenmas** [comment]
Hola, gracias por responder. Gracias por el consejo de intentar lijar el rodamiento en una superficie plana, porque al lijar con la amoladora, la rectificadora, me da miedo que el rodamiento quede con el borde torcido o inclinado. Adjunto una imagen que es mejor que tratar de explicar con palabras.

![rolamento](https://github.com/function3d/petalot/assets/142825517/7413512e-7838-424d-a297-2b17cafb576c)

ola, obrigado por responder. agradeço pela dica de tentar lixar o rolamento em uma superficie plana, pois lixando com o esmeril, a maquina esmerilhadeira, eu tenho receio de que o rolamento fique com a borda torta, ou inclinada. estou anexando uma imagem que é melhor do que tentar explicar com as palavras.

**Comment by function3d** [comment]
En realidad es preferible lo primero a lo segundo, nunca lo tercero (orden:
izquierda-derecha, arriba-abajo), me refiero a la imagen que has adjuntado,
es preferible que esté ligeramente no horizontal inclinado hacia el
interior del rodamiento, funciona igual o mejor que completamente
horizontal ya que horizontal perfecto es complicado de conseguir

**Comment by function3d** [comment]
Yo nunca uso peso, el primer corte, a mano, del culo de la botella tiene
que ser lo más recto posible si no las curvas del primer corte se
prolongarán durante todo el corte, excepto la primera vuelta, que suelo
tirar horizontalmente para que las probable rebabas del corte manual
inicial pasen fácil por la guía después elevo las manos y tiro hacia arriba
además de hacia mi, estoy trabajando en un vídeo y unas modificaciones como
son la varilla con ligera inclinación hacia atrás y guía de corte variable
durante el corte.

**Comment by function3d** [comment]
Tutorial actualizado de como hago el cortador de botellas, incluyo STLs en la descripción compatibles con vuestros actuales rodamientos tornillos y guia https://youtu.be/hEdDhRgakms?si=jsJoxt1nZHrgvoxq

**Comment by otenmas** [comment]
este seria o "bottle-cutter-2.0" ?? preferio fazer só com o 608zz?

**Comment by function3d** [comment]
De la versión inicial, desde hace tiempo, hay una versión para 608zz, por
tus fotos no tengo claro cuales son tus rodamientos pero yo llevo haciendo
cutters con el 608zz más de un año, no es que sean preferibles es que son
más fáciles de encontrar y económicos.
