### ISSUE TITLE
Dificultad con una de las piezas del nuevo cortador de botellas

### ISSUE THREAD

**Issue by JesConsuegra** [function3d/petalot#60]
Hola, en primer lugar felicitarte por el excelente rediseño del cortador, he visto el video y me ha parecido una idea estupenda, por lo que me he lanzado a convertir los mios al nuevo diseño.
La pieza base se ha impreso sin ningún problema, pero la pieza 2 (la ruleta que contiene  el tornillo) al ir a laminarla, Cura 5.6 me dice que la pieza es diminuta y la amplia automáticamente por 100.000 con lo que queda una pieza enorme que llena la base de impresión. Le he quitado un cero y con ampliación de 10.000 aparentemente sale de un tamaño correcto, se imprime correctamente pero al ponerla en la base queda un poco suelta y al meterle el tornillo sólo entra las primeras dos vueltas y con muche esfuerzo.
Podrías por favor revisar a ver si ha habido algñun problema al subir la pieza?
La he cogido de Printables.
Muchas gracias!
Jes.

**Comment by JesConsuegra** [comment]
Probado tambien con IdeaMaker 4.3.3 con el mismo resultado.
Saludos,
Jes.

**Comment by function3d** [comment]
A mí me dice algo parecido en orca slicer pero el mensaje es que parece
estar en pulgadas y que sí quiero convertirlo a milímetros y al decirle que
si me lo deja bien, tengo que investigarlo

**Comment by function3d** [comment]
Solucionado, actualizado en printables

**Comment by JesConsuegra** [comment]
Mil gracias!!
