### ISSUE TITLE
Firmware flash

### ISSUE THREAD

**Issue by AmirMahdaviAM** [function3d/petalot#61]
Hello
Sorry for silly question but, Is it mandatory to flash your firmware bin file or we can compile .ino sketch you provided and write it to wemos?

**Comment by function3d** [comment]
You can do whatever you want

**Comment by jadgood** [comment]
Hola
Cuando intento cambiar el la revoluciones no hace nada la temperatura creo que si.
Hay que cambiar los parámetros de alguna manera para que se queden guardados?

**Comment by function3d** [comment]
20 ya es el maximo
