### ISSUE TITLE
How to stick ribbons

### ISSUE THREAD

**Issue by nico97472-lab** [function3d/petalot#66]
Bonjour, 
J'aime beaucoup ton projet je m'en suis inspiré pour avoir le même fonctionnement chez moi 
Comment fais-tu pour mettre plusieurs bouteilles dans une bobine 
Comment colle-tu les rubans entre eux ?
Merci d'avance 
Bonne journée

Good morning,
I really like your project, I was inspired by it to have the same operation at home
How do you put several bottles in a reel ?
How do you glue the ribbons together ?
Thank you in advance 
have a nice day

**Comment by function3d** [comment]
I have never done that, I splice the filament
