### ISSUE TITLE
Arduino code does not compile

### ISSUE THREAD

**Issue by NickGreen98** [function3d/petalot#7]
The arduino code does not compile and therefore cannot be uploaded in that fashion.

**Comment by function3d** [comment]
Here is the result of my compilation with the libraries and versions that are used

`Using library ArduinoJson at version 6.19.4 in folder: /home/raul/Arduino/libraries/ArduinoJson 
Using library ESP8266WiFi at version 1.0 in folder: /home/raul/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WiFi 
Using library ESP8266HTTPClient at version 1.2 in folder: /home/raul/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266HTTPClient 
Using library ESP8266mDNS at version 1.2 in folder: /home/raul/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266mDNS 
Using library AccelStepper at version 1.61 in folder: /home/raul/Arduino/libraries/AccelStepper 
Using library Arduino-PID-Library-master at version 1.2.1 in folder: /home/raul/Arduino/libraries/Arduino-PID-Library-master 
Using library ESP8266WebServer at version 1.0 in folder: /home/raul/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ESP8266WebServer 
Using library ArduinoOTA at version 1.0 in folder: /home/raul/.arduino15/packages/esp8266/hardware/esp8266/3.0.2/libraries/ArduinoOTA 
/home/raul/.arduino15/packages/esp8266/tools/xtensa-lx106-elf-gcc/3.0.4-gcc10.3-1757bed/bin/xtensa-lx106-elf-size -A /tmp/arduino_build_544986/petalot.ino.elf
Sketch uses 396261 bytes (37%) of program storage space. Maximum is 1044464 bytes.
Global variables use 31108 bytes (37%) of dynamic memory, leaving 50812 bytes for local variables. Maximum is 81920 bytes.`
