### ISSUE TITLE
Bottle Cutter 608zz

### ISSUE THREAD

**Issue by seiler-emerson** [function3d/petalot#8]
Sensational project, the best I've seen so far, adjusting the height of the pet was very simple, congratulations!
Do you have a version of the bottle cutter for 608zz bearings (bearings for skates and skateboards), or could you make it?
They are much cheaper and easier to find.

**Comment by function3d** [comment]
https://github.com/function3d/petalot/blob/1d3898e29c7e2aea8eb5df6d3b6a3d68b28c794e/STLs/bottle%20Cutter%20608zz.stl
I will make a video with a better technique for sharpening the bearings.
